### PR TITLE
Feature/add switch markup extension

### PR DESCRIPTION
**Pull request by IbexPeak**
First try to create a switch/case markup extension. Unfortunately there are some issues:

1) The tests for a not setted default or null value don't pass. I expect a `DependencyProperty.UnsetValue` here, but it returns `null` both times. If I debug in the converter, it correctly returns `DependencyProperty.UnsetValue`. 

2) I want to allow the user to use a markup extension both for the key and value of the case. Currently it is only created for the key, but it doesn't work as expected both in test and view. The return value is always `null`. At the switch view, I added a "custom" color in the list box with a corresponding case inside the switch, which should evaluate the distinct custom color combobox.

Maybe you can help me with that, thanks in advance!

PS: Interestingly this PR shows the checks as "passed", but there are (above mentioned) failing tests during ci pipeline execution.

### CODE REVIEW

**Comment by MichaeIDietrich** [comment]
Thanks for extending this library and very sorry for the late reply on that.

> 1. The tests for a not setted default or null value don't pass. I expect a `DependencyProperty.UnsetValue` here, but it returns `null` both times. If I debug in the converter, it correctly returns `DependencyProperty.UnsetValue`.

Your issue with `DependencyProperty.UnsetValue` being returned as `null` value is expected to be that way (this behavior is part of the WPF framework). `DependencyProperty.UnsetValue` is used to define that a value for a property is just not set, but still requesting the value will return `default( T )` which is `null` for `object`. So you cannot test it that way. Simply set a custom value for `Default` to make your test work here. ;)

> 2. I want to allow the user to use a markup extension both for the key and value of the case. Currently it is only created for the key, but it doesn't work as expected both in test and view. The return value is always `null`. At the switch view, I added a "custom" color in the list box with a corresponding case inside the switch, which should evaluate the distinct custom color combobox.

Yeah, you face the limitations of how `Bindings` work. `Bindings` will only be evaluated when being set **directly** on a `DependencyProperty`. This is the reason almost all the `MarkupExtensions` here use `LogicalBase` as base class, since this class is designed to work around this very limitation. 

> PS: Interestingly this PR shows the checks as "passed", but there are (above mentioned) failing tests during ci pipeline execution.

Good catch! The tests actually also fail in AppVeyor but do not report it down the pipeline. I guess it is necessary to explicitly set the exit code of the PowerShell execution. I will have a look into this. Maybe I migrate to GitHub Actions for better and easier integration.

**Comment by IbexPeak** [comment]
Hi Micha,

thanks for the reply. I now modified the test for the not setted default/not null value.

For your second answer, I don't know what to do next. I just removed the view sample with the custom color. Would you see another issues in my switch extension or would you leave it like it is?

**Comment by MichaeIDietrich** [comment]
Hi, I finally took the time to look deeper into your issues and forked your branch to also support the usage of bindings in the `Switch` markup extension.
If you are good with it we could change to the forked branch as source branch for this PR.
https://github.com/MichaeIDietrich/SmartMvvm.Xaml/compare/develop...feature/Add-Switch-markup-extension

**Comment by IbexPeak** [comment]
Hi Micha,
I'm fine with that, you can change the source branch.

Thanks for helping me with this issue.

**Comment by MichaeIDietrich** [comment]
As it turns out GitHub does not support changing the source branch (unlike Azure DevOps). Could you reset (git reset --hard) your feature branch to my feature branch and force push it as I do not have the permission to modify your feature branch? If this is too much work we can alternatively close this PR and create a new with the respective source branch.

**Comment by IbexPeak** [comment]
So I failed doing a hard reset, I think it is easier to open a new branch.

**Pull request closed without merging**
